name: Fly Deploy
on:
  push:
    branches:
      - main
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
#  env:
#    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --token ${{ secrets.FLY_API_TOKEN }}